branches:
  only:
    - master
    - develop

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7
      - clang-5.0

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0"; fi
  - $CXX --version

install:
  - wget https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz
  - tar xzf 3.3.3.tar.gz
  - mv eigen-eigen-67e894c6cd8f/Eigen include/

script:
  - cd test
  - make -j 4 all
  - make test
