language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - clang
      - libeigen3-dev

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  - $CXX --version

script:
  - cd test
  - make all
  - make test
