# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spectra - C++ Library For Large Scale Eigenvalue Problems
email: yixuan.qiu@cos.name
description: A header-only C++ library for large scale eigenvalue problems
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yixuan.cos.name/spectra" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
