name: check format
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc]
        BUILD_TYPE : [Debug]
    steps:
    - uses: actions/checkout@v2 
    - name: dependencies
      run: sudo apt install libeigen3-dev clang-format-8
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: cmake -H. -Bbuild -DBUILD_TESTS=ON -DCMAKEBUILD_TYPE=${{ matrix.BUILD_TYPE }}
    - name: check_format
      run: cmake --build . --target format && git diff --exit-code
